# SEED FILE DATA:

# Doctors (Providers)
jeff = Doctor.create(name: "Dr. Jeff", email: "jeff@doctor.com")
ken = Doctor.create(name: "Dr. Ken", email: "ken@doctor.com")
amy = Doctor.create(name: "Dr. Amy", email: "amy@doctor.com")
alison = Doctor.create(name: "Dr. Alison", email: "alison@doctor.com")
robert = Doctor.create(name: "Dr. Robert", email: "robert@doctor.com")

# Patients (Clients)
mark = Patient.create(name: "Mark", email: "mark@patient.com")
albert = Patient.create(name: "Albert", email: "albert@patient.com")
peter = Patient.create(name: "Peter", email: "peter@patient.com")
lisa = Patient.create(name: "Lisa", email: "lisa@patient.com")
amanda = Patient.create(name: "Amanda", email: "amanda@patient.com")

# Plans
mark_plan_1 = Plan.create(plan_type: "basic", patient_id: mark.id, doctor_id: jeff.id)
albert_plan_1 = Plan.create(plan_type: "basic", patient_id: albert.id, doctor_id: ken.id)
peter_plan_1 = Plan.create(plan_type: "premium", patient_id: peter.id, doctor_id: amy.id)
lisa_plan_1 = Plan.create(plan_type: "premium", patient_id: lisa.id, doctor_id: alison.id)
amanda_plan_1 = Plan.create(plan_type: "basic", patient_id: amanda.id, doctor_id: robert.id)
amanda_plan_2 = Plan.create(plan_type: "premium", patient_id: amanda.id, doctor_id: amy.id)
peter_plan_2 = Plan.create(plan_type: "premium", patient_id: peter.id, doctor_id: jeff.id)
mark_plan_2 = Plan.create(plan_type: "basic", patient_id: mark.id, doctor_id: ken.id)

# Journal Entries
JournalEntry.create(content: "I'm Mark, and things are good!", patient_id: mark.id, plan_id: mark_plan_1.id)
JournalEntry.create(content: "I'm Albert, and I feel sick!", patient_id: albert.id, plan_id: albert_plan_1.id)
JournalEntry.create(content: "I'm Peter, and things are good!", patient_id: peter.id, plan_id: peter_plan_1.id)
JournalEntry.create(content: "I'm Mark, and I'm cured!!!", patient_id: mark.id, plan_id: mark_plan_2.id)
JournalEntry.create(content: "I'm Peter, and I feel sick!", patient_id: peter.id, plan_id: peter_plan_2.id)
JournalEntry.create(content: "I'm Peter, and my back hurts!", patient_id: peter.id, plan_id: peter_plan_1.id)
JournalEntry.create(content: "I'm Lisa, and things are good!", patient_id: lisa.id, plan_id: lisa_plan_1.id)
JournalEntry.create(content: "I'm Mark, and my back hurts!", patient_id: mark.id, plan_id: mark_plan_2.id)
JournalEntry.create(content: "I'm Amanda, and I'm cured!!!", patient_id: amanda.id, plan_id: amanda_plan_1.id)
JournalEntry.create(content: "I'm Lisa, and I feel sick!", patient_id: lisa.id, plan_id: lisa_plan_1.id)
JournalEntry.create(content: "I'm Peter, and I feel sick!", patient_id: peter.id, plan_id: peter_plan_2.id)
JournalEntry.create(content: "I'm Albert, and things are good!", patient_id: albert.id, plan_id: albert_plan_1.id)
JournalEntry.create(content: "I'm Amanda, and things are good!", patient_id: amanda.id, plan_id: amanda_plan_2.id)
JournalEntry.create(content: "I'm Lisa, and I'm cured!!!", patient_id: lisa.id, plan_id: lisa_plan_1.id)
JournalEntry.create(content: "I'm Peter, and I'm cured!!!", patient_id: peter.id, plan_id: peter_plan_1.id)